language: node_js
node_js:
  - node
  - 7
  - 6
  - 5
script:
  - export NODE_ENV=test
  - npm run build
  - npm run test
  - npm run lint
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 80
after_success:
  - export NODE_ENV=production
  - rm -fr ./dist
  - npm run build
  - semantic-release pre && npm publish && semantic-release post
notifications:
  email: false
sudo: false
